# Generated by Django 3.2.3 on 2021-06-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('disceiption', models.TextField()),
                ('profile_img', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Trip Number')),
            ],
        ),
    ]
